#pragma once
﻿#include <iostream>
#include <SFML/Graphics.hpp>
#include <string>
#include <math.h>
#include "settings.h"
#include "player.h"
#include "ray_casting.h"
#include "map.h"
int game_loop();
